rm(list = ls())
#################################################################################
#
# Modified PHAC S(E)IR model script with n age classes to estimate the number of
# COVID-19 cases (infected, hospitalized, etc).
#
#==================================================================================
#
#
# Author of the modifications: Maikol Diasparra, Claude Nadeau and Joel Barnes
#
# Date: 25 MAR 2020
# Last update: 8 APR 2020 
# Version: 1.0.1
#
# Modification objective: to extend the model to get the estimates by age-groups
# Original script provided by PHAC Analysts: Antoinette Ludwig & Erin Rees.
#
# But the script can be used for n age classes (e.g.age groups: 1=under 20, 2=20-59, 3=60-69, 4=70-79, 5=80+)
# Also, the differential equations are no longer hardcoded but rather built from the excel representation of the flow chart.
#
#     
# 
#################################################################################


#==========================================================================
#  packages
#==========================================================================

package_names <- c("janitor","readxl","dplyr","deSolve","tidyr","ggplot2", "ggpubr", "tidyverse") #, "viridis") 
load_packages <- lapply(package_names, require, character.only = TRUE)


### User input parameters
WDir <- "C:/Users/maiko/Downloads/SEIR_Model"             # working directory **** NO TRAILING /   akin to choose.dir()  ****
WDir <- "C:/Users/Cloud/Desktop/WORK/PHAC/SEIR-Claude/v7" # working directory **** NO TRAILING /   akin to choose.dir()  ****
#WDir <- choose.dir() # this does not generate a trailing slash or backslash
cat(WDir)  # show folder chosen
setwd(WDir)
getwd()    # show working directory

source("UtilitiesChunks.R")
source("SEIR.n.Age.Classes.R")



# BEGIN 1) compare with PHAC code : object out generated by SEIR_3.r (... and SEIR_util.r) posted on PHAC slack on April 13


file_name   = file.path(WDir,"BluePrint2 PHAC material posted on Slack on April 13(1agegrp).xls")
sheet_names = list(initial.conditions="Initial conditions",parms.1d="Parameters by Age",parms.2d="Parameters by Age x Age",model.flow="Model Specs",auxiliary.vars="Intermediate calculations")

 # make sure new_delta_Hg is used/activated in 'Model Specs'
 results.1 = SEIR.n.Age.Classes(file_name,sheet_names )

#  compare out with results.1 
 out = read.csv(paste0(WDir,"/BluePrint2 PHAC material posted on Slack on April 13/seir_3_out.csv"))
 range(results.1$solution$time)  # 0 149
 range(out$time)  #  1 150
 range(diff(results.1$solution$time)) # 1 1  --> times are in 1 unit increments
 range(diff(out$time))                # 1 1  --> times are in 1 unit increments

 shared.names = setdiff(intersect(colnames(results.1$solution),colnames(out)),"time")
 range( out[,shared.names] - results.1$solution[,shared.names]) # -0.3152966   0.3074130 some absolute differences
 range((out[,shared.names] - results.1$solution[,shared.names])/ (1e-9+ pmax(out[,shared.names] , results.1$solution[,shared.names]) ) ) #  -5.145957e-06  3.020563e-06 smallish relative differences
 range((out[,shared.names] - results.1$solution[,shared.names])/ (1e-9+ pmin(out[,shared.names] , results.1$solution[,shared.names]) ) ) #  -5.145983e-06  3.020573e-06 smallish relative differences
 
# END 1) compare with PHAC code : object out generated by SEIR_3.r (... and SEIR_util.r) posted on PHAC slack on April 13
 
# BEGIN 2) test out simpler/better way to specify hospital limited capacity (still 1 age group)
 
 # Same file_name and sheet_names as for 1).  These are reproduced below anyway 

 file_name   = file.path(WDir,"BluePrint2 PHAC material posted on Slack on April 13(1agegrp).xls")
 sheet_names = list(initial.conditions="Initial conditions",parms.1d="Parameters by Age",parms.2d="Parameters by Age x Age",model.flow="Model Specs",auxiliary.vars="Intermediate calculations")

 # make sure 'room_left_softflag*( Issq / t_severe_Hosp)'  is used/activated in 'Model Specs'.  Activate the alternative below it. 
 results.2 = SEIR.n.Age.Classes(file_name,sheet_names )
 
 range( results.2$solution  - results.1$solution ) # -900.8799  900.8475
 
 range( results.2$input.info$parms.1d$Hg_cap ) # 10000  10000  --> max capacity is 10000
 max(results.1$solution$Hg)                    #  9259.262     --> does not use  all capacity
 max(results.2$solution$Hg)                    # 10000.29      -->          uses all capacity
 
 
 matplot(results.2$solution$time, cbind(results.1$solution$Hg,results.2$solution$Hg))
 
 #View( results.2$differential.eqns.func  ) # take a look at equations used
# END 2) test out simpler/better way to specify hospital limited capacity (still 1 age group)
 
# BEGIN 3) test with 5 age groups
 
 file_name   = file.path(WDir,"BluePrint2 PHAC material posted on Slack on April 13(5agegrp).xls")
 sheet_names = list(initial.conditions="Initial conditions",parms.1d="Parameters by Age",parms.2d="Parameters by Age x Age",model.flow="Model Specs",auxiliary.vars="Intermediate calculations")

 results.5ages = SEIR.n.Age.Classes(file_name,sheet_names)
#results.5ages = SEIR.n.Age.Classes(file_name,sheet_names, differential.eqns.func= try.this.fun )
 
 range(results.5ages$solution$N_tot) # 1000100 1000100  rien ne se perd, rien ne se crée, tout se transforme
 range(results.2$solution$N_tot)     # 1000100 1000100  rien ne se perd, rien ne se crée, tout se transforme
 
 for(this.box in setdiff(colnames(results.2$solution),c( "time","N_tot" )) )
 {
   somme = apply(results.5ages$solution[,paste0(this.box,1:5)],1,sum)
   cat("\n",this.box, range(results.2$solution[,this.box] - somme) )   # fairly good agreement between results.2 and results.5ages
 }
   
 matplot(results.5ages$solution$time,results.5ages$solution[,paste0("Sg",1:5)],type="l",xlab="time") # plotting without ggplot2 just like a dynosaur.
 
 # END 3) test with 5 age groups
 
 # BEGIN 4) parameter sweep with example 2)
 
 file_name   = file.path(WDir,"BluePrint2 PHAC material posted on Slack on April 13(1agegrp).xls")
 sheet_names = list(initial.conditions="Initial conditions",parms.1d="Parameters by Age",parms.2d="Parameters by Age x Age",model.flow="Model Specs",auxiliary.vars="Intermediate calculations")

 sheet_names_for_sweep = sheet_names        # provide sheet names used in results (results.sheet.v2.good)
 
   baseline.parms.1d = results.2$input.info$parms.1d  # data frame of 1d parameters
   list.sweep = list() #        store results in list  ... 
   df.sweep = c()      # ... or store results in data.frame
   for(log.fudge.factor in seq(-0.5,0.5,0.25))
   {
     cat("\n Doing log.fudge.factor=",log.fudge.factor)
     this.label = paste("sigma multiplied by",exp(log.fudge.factor))
     parms.1d = baseline.parms.1d  # data frame of 1d parameters
     parms.1d$t_latency = parms.1d$t_latency * exp(log.fudge.factor) # alter t_latency as per parameter sweep
     sheet_names_for_sweep$parms.1d = parms.1d
     this.result = SEIR.n.Age.Classes(file_name,sheet_names_for_sweep) 
     list.sweep[[this.label]] = this.result$solution
     this.result$solution$this.label = this.label
     df.sweep = rbind(df.sweep,this.result$solution)
     
   }
   range(list.sweep$"sigma multiplied by 1" - results.2$solution) # same      as expected
   range(list.sweep[[ 3 ]]                  - results.2$solution) # same      as expected
   range(list.sweep[[ 2 ]]                  - results.2$solution) # different as expected
   
   extract.df = subset(df.sweep,this.label == "sigma multiplied by 1")
   extract.df$this.label = c()
   range(extract.df - results.2$solution) # same      as expected
   
   # quick crack at plotting. Can plot much better ... but good enough for proof of concept
   plot(subset(df.sweep,time<50)$time , subset(df.sweep,time<50)$Sg,type="l") 
 
 
# END 4) parameter sweep with example 2)
   


